/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/scene.gltf -o src/components/BrakeDiscModel.jsx 
Author: DRIVER-FIRE (https://sketchfab.com/DRIVER-FIRE)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/6-lug-brake-rotor-and-brembo-brake-calipers-ef37be6ddce44f49b6f616145c1e16af
Title: 6- Lug Brake Rotor and Brembo brake calipers
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.color_12568524} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.color_14541540} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.color_15277357} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.color_16448250} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
